version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app               # Sync local files
      - /app/node_modules    # Keep container's node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching
      - WATCHPACK_POLLING=true    # For Webpack
    command: npm run dev